### ISSUE TITLE
Interested in learning

### ISSUE THREAD

**Issue by journeytosilius** [AlexEne/rust-particles#2]
Hi, I have watched your two videos on Rust and OpenGL, and I wanted to ask you if you can reference a book or some material that I can use on how to implement OpenGL with Rust? I am currently writing in Rust but I have no idea on how where to find a good tutorial or book about it. Thanks !

**Comment by AlexEne** [comment]
I learned from [modern opengl tutorial](https://learnopengl.com/) and used the [gl](https://crates.io/search?q=gl) crate.

This helped me as the gl crate just exposes any opengl function in an easy way: `glClear` becomes `gl::Clear`.


If you want to go into compute shaders, I've found no good reference besides: [OpenGL SuperBible](https://www.amazon.co.uk/OpenGL-Superbible-Comprehensive-Tutorial-Reference/dp/0672337479/ref=sr_1_1?keywords=opengl+superbible&qid=1563182526&s=gateway&sr=8-1)

**Comment by journeytosilius** [comment]
Thanks this was helpful !
